#!/bin/sh
#
# Copyright 2019 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu
TEST_DIR=/tmp/lightning_test_result
# --ca "$TEST_DIR/tls/ca.pem" \
# --cert "$TEST_DIR/tls/lightning.pem" \
# --key "$TEST_DIR/tls/lightning.key" \
# -test.blockprofile="$TEST_DIR/block.$TEST_NAME.$$.out" \
# -test.cpuprofile="$TEST_DIR/cpu.$TEST_NAME.$$.out" \
# -test.memprofile="$TEST_DIR/mem.$TEST_NAME.$$.out" DEVEL \
echo "[$(date)] <<<<<< RUNNING TEST FOR: tests/$TEST_NAME $@ >>>>>>" >> "$TEST_DIR/lightning.log"
bin/tidb-lightning.test -test.coverprofile="$TEST_DIR/cov.$TEST_NAME.$$.out" DEVEL \
    --log-file "$TEST_DIR/lightning.log" \
    --tidb-port 3390 \
    --pd-urls '127.0.0.1:2379' \
    --config "tests/$TEST_NAME/config.toml" \
    -d "tests/$TEST_NAME/data" \
    --importer '127.0.0.1:8808' \
    --sorted-kv-dir "$TEST_DIR/sorted" \
    --enable-checkpoint=0 \
    --check-requirements=0 \
    "$@"
